#!/usr/bin/env python3
import argparse
import csv
import json
import math
import os
import struct
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterator, List, Optional

from tensorboard.compat.proto import event_pb2


@dataclass
class RunInspection:
    run_dir: Path
    target_iters: int
    progress_iters: int
    is_done: bool
    done_reason: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect MetaWorldSimple queue job status from run directories."
    )
    parser.add_argument(
        "--jobs-file",
        type=Path,
        required=True,
        help="TSV manifest generated by the queue launcher.",
    )
    parser.add_argument(
        "--session-dir",
        type=Path,
        required=True,
        help="Queue session directory containing pids/ and meta/.",
    )
    parser.add_argument(
        "--completion-ratio",
        type=float,
        default=0.95,
        help="Treat a finished, exited run as done when progress reaches this ratio.",
    )
    parser.add_argument(
        "--output-format",
        type=str,
        choices=("tsv", "json"),
        default="tsv",
        help="Output format.",
    )
    return parser.parse_args()


def iter_tfrecord_records(path: Path) -> Iterator[bytes]:
    with path.open("rb") as file:
        while True:
            header = file.read(8)
            if not header or len(header) < 8:
                break
            (length,) = struct.unpack("<Q", header)
            _ = file.read(4)
            payload = file.read(length)
            _ = file.read(4)
            if len(payload) != length:
                break
            yield payload


def read_max_scalar_step(run_dir: Path) -> int:
    max_scalar_step = -1
    event_files = sorted(run_dir.glob("events.out.tfevents.*"))
    for event_file in event_files:
        for payload in iter_tfrecord_records(event_file):
            event = event_pb2.Event()
            try:
                event.ParseFromString(payload)
            except Exception:
                continue
            if not event.summary.value:
                continue
            step = int(event.step)
            if step > max_scalar_step:
                max_scalar_step = step
    return max_scalar_step


def read_run_target_iters(run_dir: Path, fallback_train_iters: int) -> int:
    args_path = run_dir / "args.json"
    if args_path.exists():
        try:
            payload = json.loads(args_path.read_text(encoding="utf-8"))
            train_iters = int(payload.get("train_iters", fallback_train_iters))
            if train_iters > 0:
                return train_iters
        except Exception:
            pass
    return fallback_train_iters


def inspect_run_dir(
    run_dir: Path,
    fallback_train_iters: int,
    completion_ratio: float,
) -> RunInspection:
    target_iters = read_run_target_iters(run_dir, fallback_train_iters)
    max_scalar_step = read_max_scalar_step(run_dir)
    progress_iters = max_scalar_step + 1 if max_scalar_step >= 0 else 0

    required_iters = 0
    if target_iters > 0:
        required_iters = max(1, math.ceil(target_iters * completion_ratio))

    final_checkpoint_exists = False
    if target_iters > 0:
        final_checkpoint = run_dir / "checkpoints" / f"simple_state_iter_{target_iters - 1}.pt"
        final_checkpoint_exists = final_checkpoint.exists()
        if final_checkpoint_exists and progress_iters < target_iters:
            progress_iters = target_iters

    is_done = False
    done_reason = ""
    if final_checkpoint_exists:
        is_done = True
        done_reason = "final_checkpoint"
    elif required_iters > 0 and progress_iters >= required_iters:
        is_done = True
        done_reason = "completion_ratio"

    return RunInspection(
        run_dir=run_dir,
        target_iters=target_iters,
        progress_iters=progress_iters,
        is_done=is_done,
        done_reason=done_reason,
    )


def is_pid_running(pid: Optional[int]) -> bool:
    if pid is None or pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def read_pid(session_dir: Path, job_key: str) -> Optional[int]:
    pid_path = session_dir / "pids" / f"{job_key}.pid"
    if not pid_path.exists():
        return None
    try:
        value = pid_path.read_text(encoding="utf-8").strip()
        return int(value) if value else None
    except Exception:
        return None


def read_meta(session_dir: Path, job_key: str) -> Dict[str, str]:
    meta_path = session_dir / "meta" / f"{job_key}.json"
    if not meta_path.exists():
        return {}
    try:
        payload = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return {str(key): str(value) for key, value in payload.items() if value is not None}


def collect_matching_run_dirs(task_runs_root: Path, exp_name: str) -> List[Path]:
    if not task_runs_root.exists():
        return []
    candidates = [
        candidate
        for candidate in sorted(task_runs_root.glob(f"{exp_name}_*"))
        if candidate.is_dir()
    ]
    return candidates


def inspect_job(
    row: Dict[str, str],
    session_dir: Path,
    completion_ratio: float,
) -> Dict[str, str]:
    job_key = row["job_key"]
    fallback_train_iters = int(row["train_iters"])
    task_runs_root = Path(row["task_runs_root"])
    exp_name = row["exp_name"]

    meta = read_meta(session_dir, job_key)
    pid = read_pid(session_dir, job_key)
    pid_alive = is_pid_running(pid)

    run_dirs = collect_matching_run_dirs(task_runs_root, exp_name)
    inspections = [
        inspect_run_dir(run_dir, fallback_train_iters=fallback_train_iters, completion_ratio=completion_ratio)
        for run_dir in run_dirs
    ]
    latest_inspection = inspections[-1] if inspections else None
    done_inspections = [inspection for inspection in inspections if inspection.is_done]

    status = "missing"
    selected = None
    stale_run_dirs: List[str] = []
    done_reason = ""

    if pid_alive:
        status = "running"
        selected = latest_inspection
    elif done_inspections:
        status = "done"
        selected = done_inspections[-1]
        done_reason = selected.done_reason
    elif inspections:
        status = "stale"
        selected = latest_inspection
        stale_run_dirs = [str(inspection.run_dir) for inspection in inspections]

    last_iter = selected.progress_iters if selected is not None else 0
    target_iters = selected.target_iters if selected is not None else fallback_train_iters
    progress_ratio = (float(last_iter) / float(target_iters)) if target_iters > 0 else 0.0
    gpu_id = meta.get("gpu_id") or "-"
    log_file = meta.get("log_file") or "-"
    run_dir_value = str(selected.run_dir) if selected is not None else "-"
    stale_run_dirs_value = "|".join(stale_run_dirs) if stale_run_dirs else "-"
    done_reason_value = done_reason or "-"

    return {
        "job_index": row["job_index"],
        "job_key": job_key,
        "task_name": row["task_name"],
        "clip_mode": row["clip_mode"],
        "sigma": row["sigma"],
        "seed": row["seed"],
        "status": status,
        "pid": str(pid) if pid is not None else "-",
        "pid_alive": "1" if pid_alive else "0",
        "gpu_id": gpu_id,
        "last_iter": str(last_iter),
        "target_iters": str(target_iters),
        "progress_ratio": f"{progress_ratio:.6f}",
        "done_reason": done_reason_value,
        "run_dir": run_dir_value,
        "stale_run_dirs": stale_run_dirs_value,
        "log_file": log_file,
    }


def read_jobs(jobs_file: Path) -> List[Dict[str, str]]:
    with jobs_file.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file, delimiter="\t")
        return [dict(row) for row in reader]


def emit_tsv(rows: List[Dict[str, str]]) -> None:
    fieldnames = [
        "job_index",
        "job_key",
        "task_name",
        "clip_mode",
        "sigma",
        "seed",
        "status",
        "pid",
        "pid_alive",
        "gpu_id",
        "last_iter",
        "target_iters",
        "progress_ratio",
        "done_reason",
        "run_dir",
        "stale_run_dirs",
        "log_file",
    ]
    writer = csv.DictWriter(
        sys.stdout,
        fieldnames=fieldnames,
        delimiter="\t",
        lineterminator="\n",
    )
    writer.writeheader()
    for row in rows:
        writer.writerow(row)


def main() -> None:
    args = parse_args()
    jobs = read_jobs(args.jobs_file)
    rows = [
        inspect_job(row, session_dir=args.session_dir, completion_ratio=args.completion_ratio)
        for row in jobs
    ]

    if args.output_format == "json":
        json.dump(rows, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
        return

    emit_tsv(rows)


if __name__ == "__main__":
    main()
