denoiser:
  _target_: envs.diffusion.denoiser.DenoiserConfig
  sigma_data: 0.5
  sigma_offset_noise: 0.3
  inner_model:
    _target_: envs.diffusion.inner_model.InnerModelConfig
    img_channels: 3
    num_steps_conditioning: 4
    cond_channels: 256
    depths: [2,2,2,2]
    channels: [64,64,64,64]
    attn_depths: [0,0,0,0]

reward_model:
  focal_alpha: 0.99  # Focal loss alpha parameter for reward model
  
#denoiser_path: "/cpfs01/jinshiji_workspace/diamond/checkpoints/checkpoint_step_543900.pt"
#reward_model_path: "/cpfs01/jinshiji_workspace/openvla_oft_rl/runs/reward_model/20251222_111317_reward_model/best_model.pt"
#openvla_path: "/cpfs01/liuwei_workspace/models/finetune_im/openvla-7b+libero_spatial_no_noops+b32+lr-0.0005+lora-r32+dropout-0.0--image_aug--parallel_dec--8_acts_chunk--discrete_acts--proprio_state--100000_chkpt"
#checkpoint2_path: "/cpfs01/lcx_workspace/openvla-oft/runs/distill/20251225_113851_distill/checkpoints/checkpoint_latest.pt"
#denoiser_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl/runs/denoiser/object0_v3/best_val.pt"
#reward_model_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl/runs/reward_model/transferred_model/best_model.pt"
#openvla_path: "/mnt/data/lcx2/yanjieworkspace/models/finetune_im/openvla-7b+libero_spatial_no_noops+b32+lr-0.0005+lora-r32+dropout-0.0--image_aug--parallel_dec--8_acts_chunk--discrete_acts--proprio_state--100000_chkpt"
#checkpoint2_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl_from_oss/runs/distill_quick_test/20260608_164220_object_task0_distill_1img_nopro_150/checkpoints/checkpoint_latest.pt"
denoiser_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl/runs/wm_reward_denoiser_distill_named/denoiser_smoke_test/denoiser_smoke_test.pt"
reward_model_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl/runs/wm_reward_denoiser_distill_named/reward_model_object0_alpha_0d95_epoch15_v2/best_model.pt"
openvla_path: "/mnt/data/lcx3/checkpoint/dsj/openvla-7b+libero_spatial_no_noops+b32+lr-0.0005+lora-r32+dropout-0.0--image_aug--parallel_dec--8_acts_chunk--discrete_acts--proprio_state--100000_chkpt"
#checkpoint2_path: "/mnt/data/lcx2/yanjieworkspace/openvla_oft_rl/runs/wm_reward_denoiser_distill_named/distill_object_teacher_2img_proprio_student_1img_no_proprio/checkpoint_step_100.pt"
checkpoint2_path: ""