world_model_env:
  _target_: world_model_env.WorldModelEnvConfig
  horizon: 15
  num_batches_to_preload: 256
  diffusion_sampler:
    _target_: diffusion.DiffusionSamplerConfig
    num_steps_denoising: 3
    sigma_min: 2e-3
    sigma_max: 5.0
    rho: 7
    order: 1  # 1: Euler, 2: Heun
    s_churn: 0.0  # Amount of stochasticity
    s_tmin: 0.0
    s_tmax: ${eval:'float("inf")'}
    s_noise: 1.0

denoiser:
  training:
    num_autoregressive_steps: 1
    start_after_epochs: 0
    steps_first_epoch: 10
    steps_per_epoch: 4
    sample_weights: [0.1, 0.1, 0.1, 0.7]
    batch_size: 32
    grad_acc_steps: 1
    lr_warmup_steps: 100
    max_grad_norm: 1.0

  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
    eps: 1e-8
  
  sigma_distribution: # log normal distribution for sigma during training
    _target_: diffusion.SigmaDistributionConfig
    loc: -0.4
    scale: 1.2
    sigma_min: 2e-3
    sigma_max: 20

reward_model:
  focal_alpha: 0.99  # Focal loss alpha parameter for reward model
  pretrained_checkpoint: "/cpfs01/liuwei_workspace/models/finetune_im/openvla-7b+libero_spatial_no_noops+b32+lr-0.0005+lora-r32+dropout-0.0--image_aug--parallel_dec--8_acts_chunk--discrete_acts--proprio_state--100000_chkpt"