METAWORLD_INSTRUCTIONS = {
    'assembly-v3': 'Assemble the disassembled object by fitting the parts together correctly.',
    'basketball-v3': 'Pick up the basketball and shoot it into the hoop.',
    'bin-picking-v3': 'Pick up the object from inside the bin and place it outside.',
    'box-close-v3': 'Close the box by lowering the lid until it clicks into place.',
    'button-press-topdown-v3': 'Press the button vertically downward until it is fully depressed.',
    'button-press-topdown-wall-v3': 'Reach over the wall and press the button downward until it clicks.',
    'button-press-v3': 'Press the button until it is fully activated.',
    'button-press-wall-v3': 'Press the button through the opening in the wall.',
    'coffee-button-v3': 'Press the coffee machine\'s button to start brewing.',
    'coffee-pull-v3': 'Pull the coffee machine\'s lever to dispense coffee.',
    'coffee-push-v3': 'Push the coffee machine\'s lever back to its original position.',
    'dial-turn-v3': 'Rotate the dial clockwise or counterclockwise to the target setting.',
    'disassemble-v3': 'Carefully take apart the assembled object.',
    'door-close-v3': 'Gently close the door until it shuts completely.',
    'door-lock-v3': 'Turn the lock mechanism to secure the door.',
    'door-open-v3': 'Pull the door handle to open it fully.',
    'door-unlock-v3': 'Turn the key or latch to unlock the door.',
    'hand-insert-v3': 'Insert your hand into the narrow slot until it reaches the end.',
    'drawer-close-v3': 'Push the drawer gently until it is fully closed.',
    'drawer-open-v3': 'Pull the drawer handle to open it completely.',
    'faucet-open-v3': 'Turn the faucet handle to let water flow.',
    'faucet-close-v3': 'Turn the faucet handle to stop the water.',
    'hammer-v3': 'Swing the hammer to hit the nail into the surface.',
    'handle-press-side-v3': 'Press the side handle downward until it clicks.',
    'handle-press-v3': 'Push the handle straight down to activate it.',
    'handle-pull-side-v3': 'Pull the side handle outward to release it.',
    'handle-pull-v3': 'Pull the handle upward or outward to engage the mechanism.',
    'lever-pull-v3': 'Pull the lever down to trigger the connected system.',
    'pick-place-wall-v3': 'Pick up the object and place it on the shelf against the wall.',
    'pick-out-of-hole-v3': 'Retrieve the object from inside the hole and lift it out.',
    'pick-place-v3': 'Grasp the object and move it to the target location.',
    'plate-slide-v3': 'Slide the plate horizontally to the marked position.',
    'plate-slide-side-v3': 'Push the plate sideways along its track.',
    'plate-slide-back-v3': 'Slide the plate backward to its starting position.',
    'plate-slide-back-side-v3': 'Move the plate diagonally backward along the side rail.',
    'peg-insert-side-v3': 'Insert the peg into the hole from the side until it fits snugly.',
    'peg-unplug-side-v3': 'Remove the peg by pulling it sideways out of the hole.',
    'soccer-v3': 'Kick the soccer ball into the goal.',
    'stick-push-v3': 'Push the stick forward to move the connected object.',
    'stick-pull-v3': 'Pull the stick backward to disengage the mechanism.',
    'push-v3': 'Push the object forward until it reaches the target.',
    'push-wall-v3': 'Push the object through the gap in the wall.',
    'push-back-v3': 'Push the object backward to its original position.',
    'reach-v3': 'Move the hand to touch the target point.',
    'reach-wall-v3': 'Reach toward the target point located behind the wall.',
    'shelf-place-v3': 'Place the object onto the designated shelf.',
    'sweep-into-v3': 'Sweep the debris into the hole or container.',
    'sweep-v3': 'Use the broom to sweep the scattered objects together.',
    'window-open-v3': 'Slide the window open fully.',
    'window-close-v3': 'Slide the window shut until it is fully closed.'
}