#!/usr/bin/env python3
"""Measure brush-to-trace-tip distance for every contact frame in a run."""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import deque
from dataclasses import dataclass, replace
from pathlib import Path

import cv2
import numpy as np

from detect_brush_contact_distance import (
    annotate_distance,
    detect_brush_contact,
)
from detect_hollow_trace import HollowTraceDetection, detect_hollow_trace


@dataclass
class ReferenceChoice:
    trace: HollowTraceDetection
    roi: tuple[int, int, int, int]
    background: np.ndarray
    trace_reference_source: str
    background_reference_source: str
    trace_reference_frame: int | None
    background_reference_frame: int
    selection_method: str


@dataclass
class TraceCandidate:
    frame_index: int
    roi: tuple[int, int, int, int]
    detection: HollowTraceDetection

    @property
    def global_tip(self) -> np.ndarray:
        return np.array(
            [
                self.detection.tip_x + self.roi[0],
                self.detection.tip_y + self.roi[1],
            ],
            dtype=float,
        )

    @property
    def global_center(self) -> np.ndarray:
        return np.array(
            [
                self.detection.center_x + self.roi[0],
                self.detection.center_y + self.roi[1],
            ],
            dtype=float,
        )


def _trace_basis(angle_deg: float) -> tuple[np.ndarray, np.ndarray]:
    angle = math.radians(angle_deg)
    axis = np.array([math.cos(angle), math.sin(angle)], dtype=float)
    if axis[0] < 0:
        axis = -axis
    return axis, np.array([-axis[1], axis[0]], dtype=float)


def _panel(image: np.ndarray, title: str, width: int = 640) -> np.ndarray:
    height = int(round(image.shape[0] * width / image.shape[1]))
    panel = cv2.resize(image, (width, height), interpolation=cv2.INTER_AREA)
    cv2.rectangle(panel, (0, 0), (280, 27), (255, 255, 255), -1)
    cv2.putText(
        panel,
        title,
        (7, 19),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.52,
        (25, 25, 25),
        1,
        cv2.LINE_AA,
    )
    return panel


def _valid_roi(
    roi: tuple[int, int, int, int], image_shape: tuple[int, int]
) -> bool:
    x, y, width, height = roi
    image_height, image_width = image_shape
    return (
        x >= 0
        and y >= 0
        and width > 0
        and height > 0
        and x + width <= image_width
        and y + height <= image_height
    )


def _crop(image: np.ndarray, roi: tuple[int, int, int, int]) -> np.ndarray:
    x, y, width, height = roi
    return image[y : y + height, x : x + width].copy()


def _search_rois(
    image_shape: tuple[int, int], preferred: tuple[int, int, int, int]
) -> list[tuple[int, int, int, int]]:
    image_height, image_width = image_shape
    candidates: list[tuple[int, int, int, int]] = []

    def add(roi: tuple[int, int, int, int]) -> None:
        if _valid_roi(roi, image_shape) and roi not in candidates:
            candidates.append(roi)

    add(preferred)
    preferred_x, _, preferred_width, preferred_height = preferred
    search_width = min(preferred_width, image_width)
    search_x = min(max(0, preferred_x), image_width - search_width)
    search_height = min(max(360, preferred_height), image_height)
    last_y = image_height - search_height
    # The configured ROI identifies the paper band approximately.  Search
    # downward to accommodate camera/paper movement, plus a small upward
    # margin, but do not scan unrelated long boxes at the top of the image.
    first_y = min(last_y, max(0, preferred[1] - 30))
    for y in list(range(first_y, last_y + 1, 150)) + [last_y]:
        add((search_x, y, search_width, search_height))
    return candidates


def _sample_indices(count: int, preferred_index: int, samples: int) -> list[int]:
    indices = {0, count - 1, preferred_index}
    indices.update(
        int(round(value))
        for value in np.linspace(0, count - 1, min(samples, count))
    )
    return sorted(index for index in indices if 0 <= index < count)


def _read_image(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"could not read image: {path}")
    return image


def _prepare_output_dir(output_dir: Path) -> Path:
    """Remove only files generated by an earlier conversion of this run."""
    output_dir.mkdir(parents=True, exist_ok=True)
    annotated_dir = output_dir / "annotated"
    annotated_dir.mkdir(parents=True, exist_ok=True)
    for path in annotated_dir.glob("frame_*.jpg"):
        path.unlink()
    for name in ("contact_sheet.jpg", "report.json"):
        path = output_dir / name
        if path.exists():
            path.unlink()
    return annotated_dir


def _same_trace(first: TraceCandidate, second: TraceCandidate) -> bool:
    first_length = first.detection.length_px
    second_length = second.detection.length_px
    length_ratio = min(first_length, second_length) / max(
        first_length, second_length, 1.0
    )
    return (
        np.linalg.norm(first.global_tip - second.global_tip) <= 120.0
        and np.linalg.norm(first.global_center - second.global_center) <= 180.0
        and length_ratio >= 0.65
        and abs(first.detection.angle_deg - second.detection.angle_deg) <= 8.0
    )


def _select_consistent_trace(records: list[TraceCandidate]) -> TraceCandidate:
    """Prefer geometry repeated across sampled frames over a high-score outlier."""
    clusters: list[list[TraceCandidate]] = []
    for record in records:
        for cluster in clusters:
            if _same_trace(cluster[0], record):
                cluster.append(record)
                break
        else:
            clusters.append([record])

    def cluster_key(cluster: list[TraceCandidate]) -> tuple[int, float]:
        frame_support = len({record.frame_index for record in cluster})
        median_score = float(
            np.median([record.detection.score for record in cluster])
        )
        return frame_support, median_score

    cluster = max(clusters, key=cluster_key)
    median_tip = np.median(
        np.asarray([record.global_tip for record in cluster]), axis=0
    )
    median_center = np.median(
        np.asarray([record.global_center for record in cluster]), axis=0
    )
    median_length = float(
        np.median([record.detection.length_px for record in cluster])
    )

    def geometry_error(record: TraceCandidate) -> float:
        tip_error = float(np.linalg.norm(record.global_tip - median_tip))
        center_error = float(np.linalg.norm(record.global_center - median_center))
        length_error = abs(record.detection.length_px - median_length)
        return tip_error + 0.5 * center_error + 0.25 * length_error

    return min(
        cluster,
        key=lambda record: (geometry_error(record), -record.detection.score),
    )


def _choose_reference(
    images: list[Path],
    preferred_frame: int,
    preferred_roi: tuple[int, int, int, int],
    auto_search: bool,
    search_samples: int,
) -> ReferenceChoice:
    preferred_index = preferred_frame - 1
    preferred_full = _read_image(images[preferred_index])
    if not _valid_roi(preferred_roi, preferred_full.shape[:2]):
        raise RuntimeError(
            f"configured ROI {preferred_roi} lies outside "
            f"{preferred_full.shape[1]}x{preferred_full.shape[0]}"
        )

    preferred_detection: HollowTraceDetection | None = None
    try:
        preferred_crop = _crop(preferred_full, preferred_roi)
        preferred_detection = detect_hollow_trace(preferred_crop)
    except RuntimeError:
        if not auto_search:
            raise RuntimeError(
                f"no trace in configured frame {preferred_frame} and ROI "
                f"{preferred_roi}; enable --auto-search or choose another reference"
            )

    if preferred_detection is not None and not auto_search:
        return ReferenceChoice(
            trace=preferred_detection,
            roi=preferred_roi,
            background=preferred_crop,
            trace_reference_source=str(images[preferred_index]),
            background_reference_source=str(images[preferred_index]),
            trace_reference_frame=preferred_frame,
            background_reference_frame=preferred_frame,
            selection_method="configured",
        )

    rois = _search_rois(preferred_full.shape[:2], preferred_roi)
    records: list[TraceCandidate] = []
    for frame_index in _sample_indices(
        len(images), preferred_index, max(2, search_samples)
    ):
        full = _read_image(images[frame_index])
        if full.shape != preferred_full.shape:
            continue
        for roi in rois:
            try:
                detection = detect_hollow_trace(_crop(full, roi))
            except RuntimeError:
                continue
            records.append(
                TraceCandidate(
                    frame_index=frame_index,
                    roi=roi,
                    detection=detection,
                )
            )

    if not records:
        sample_count = len(
            _sample_indices(len(images), preferred_index, max(2, search_samples))
        )
        raise RuntimeError(
            f"no visible hollow trace in {sample_count} sampled frames "
            "or any automatic ROI"
        )

    # A transient ink split or background edge can receive a high single-frame
    # score.  Select geometry supported by the most sampled frames, then use
    # the member nearest that cluster's median geometry as the reference.
    selected = _select_consistent_trace(records)
    frame_index = selected.frame_index
    roi = selected.roi
    trace = selected.detection
    background = _crop(preferred_full, roi)
    return ReferenceChoice(
        trace=trace,
        roi=roi,
        background=background,
        trace_reference_source=str(images[frame_index]),
        background_reference_source=str(images[preferred_index]),
        trace_reference_frame=frame_index + 1,
        background_reference_frame=preferred_frame,
        selection_method="auto_search_consensus",
    )


def _choice_from_template(
    template_report_path: Path,
    images: list[Path],
    background_frame: int,
) -> ReferenceChoice:
    try:
        template_report = json.loads(template_report_path.read_text(encoding="utf-8"))
        if template_report.get("status") != "ok":
            raise ValueError("report status is not 'ok'")
        roi = tuple(int(value) for value in template_report["roi_xywh"])
        if len(roi) != 4:
            raise ValueError("roi_xywh must contain exactly four integers")
        trace_source = Path(template_report["trace_reference_source"])
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        raise RuntimeError(
            f"invalid trace template report {template_report_path}: {error}"
        ) from error

    trace_full = _read_image(trace_source)
    background_full = _read_image(images[background_frame - 1])
    if trace_full.shape != background_full.shape:
        raise RuntimeError(
            "trace template and current images have different resolutions: "
            f"{trace_full.shape} vs {background_full.shape}"
        )
    if not _valid_roi(roi, trace_full.shape[:2]):
        raise RuntimeError(f"template ROI {roi} is outside the current image")
    trace = detect_hollow_trace(_crop(trace_full, roi))
    return ReferenceChoice(
        trace=trace,
        roi=roi,
        background=_crop(background_full, roi),
        trace_reference_source=str(trace_source),
        background_reference_source=str(images[background_frame - 1]),
        trace_reference_frame=None,
        background_reference_frame=background_frame,
        selection_method=f"template:{template_report_path}",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sequence_dir", type=Path)
    parser.add_argument(
        "--reference-frame",
        type=int,
        required=True,
        help="One-based frame with a visible trace and no paper contact",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--median-window", type=int, default=5)
    parser.add_argument("--mm-per-pixel", type=float)
    parser.add_argument(
        "--roi",
        type=int,
        nargs=4,
        metavar=("X", "Y", "WIDTH", "HEIGHT"),
        help="Optional crop containing the target trace",
    )
    parser.add_argument(
        "--auto-search",
        action="store_true",
        help="Search sampled frames and vertical ROIs if configured detection fails",
    )
    parser.add_argument(
        "--search-samples",
        type=int,
        default=12,
        help="Number of evenly spaced frames checked by --auto-search",
    )
    parser.add_argument(
        "--trace-template-report",
        type=Path,
        help="Previous successful report used only when this run has no visible trace",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    images = sorted(args.sequence_dir.glob("*.jpg"))
    if not images:
        print(f"[ERROR] no JPG frames found in {args.sequence_dir}", file=sys.stderr)
        return 2
    if not 1 <= args.reference_frame <= len(images):
        print(
            f"[ERROR] reference frame {args.reference_frame} is outside 1..{len(images)}",
            file=sys.stderr,
        )
        return 2
    if args.median_window < 1:
        print("[ERROR] median window must be at least 1", file=sys.stderr)
        return 2
    if args.search_samples < 2:
        print("[ERROR] search samples must be at least 2", file=sys.stderr)
        return 2

    annotated_dir = _prepare_output_dir(args.output_dir)

    try:
        first_full = _read_image(images[args.reference_frame - 1])
    except RuntimeError as error:
        print(f"[ERROR] {error}", file=sys.stderr)
        return 2
    configured_roi = tuple(args.roi) if args.roi else (
        0,
        0,
        first_full.shape[1],
        first_full.shape[0],
    )
    try:
        choice = _choose_reference(
            images,
            args.reference_frame,
            configured_roi,
            args.auto_search,
            args.search_samples,
        )
    except RuntimeError as search_error:
        if args.trace_template_report is None:
            args.output_dir.mkdir(parents=True, exist_ok=True)
            failure_report = {
                "status": "failed",
                "sequence_dir": str(args.sequence_dir),
                "source_count": len(images),
                "error": str(search_error),
            }
            report_path = args.output_dir / "report.json"
            report_path.write_text(
                json.dumps(failure_report, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            print(f"[ERROR] {search_error}", file=sys.stderr)
            print(f"[ERROR] failure report: {report_path}", file=sys.stderr)
            return 3
        try:
            choice = _choice_from_template(
                args.trace_template_report, images, args.reference_frame
            )
        except RuntimeError as template_error:
            args.output_dir.mkdir(parents=True, exist_ok=True)
            failure_report = {
                "status": "failed",
                "sequence_dir": str(args.sequence_dir),
                "source_count": len(images),
                "error": str(search_error),
                "template_error": str(template_error),
                "trace_template_report": str(args.trace_template_report),
            }
            report_path = args.output_dir / "report.json"
            report_path.write_text(
                json.dumps(failure_report, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            print(
                f"[ERROR] automatic search failed: {search_error}; "
                f"template fallback failed: {template_error}",
                file=sys.stderr,
            )
            print(f"[ERROR] failure report: {report_path}", file=sys.stderr)
            return 3

    trace = choice.trace
    roi_x, roi_y, roi_width, roi_height = choice.roi
    reference = choice.background
    axis, normal = _trace_basis(trace.angle_deg)

    history: deque[tuple[float, float]] = deque(maxlen=args.median_window)
    last_contact_frame: int | None = None
    report_frames = []
    rendered: list[tuple[int, np.ndarray]] = []

    for frame_number, path in enumerate(images, 1):
        full_image = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if full_image is None:
            continue
        if not _valid_roi(choice.roi, full_image.shape[:2]):
            continue
        image = _crop(full_image, choice.roi)
        try:
            raw = detect_brush_contact(image, reference, trace)
        except RuntimeError:
            continue
        if not raw.touching_trace:
            continue

        # A gap means a new contact episode.  Do not carry the median from an
        # old click into a later click at another location.
        if last_contact_frame is None or frame_number != last_contact_frame + 1:
            history.clear()
        history.append((raw.contact_x, raw.contact_y))
        last_contact_frame = frame_number
        stable_x, stable_y = np.median(np.asarray(history), axis=0)
        delta = np.array([stable_x - trace.tip_x, stable_y - trace.tip_y])
        axial = float(delta @ axis)
        lateral = float(delta @ normal)
        distance = float(np.linalg.norm(delta))
        stable = replace(
            raw,
            contact_x=float(stable_x),
            contact_y=float(stable_y),
            distance_px=distance,
            axial_distance_px=axial,
            lateral_offset_px=lateral,
        )
        marked_crop = annotate_distance(
            image,
            trace,
            stable,
            args.mm_per_pixel,
            coordinate_offset=(roi_x, roi_y),
        )
        annotated = full_image.copy()
        annotated[
            roi_y : roi_y + roi_height, roi_x : roi_x + roi_width
        ] = marked_crop
        output = annotated_dir / f"frame_{frame_number:03d}_{path.stem}.jpg"
        cv2.imwrite(str(output), annotated, [cv2.IMWRITE_JPEG_QUALITY, 95])
        rendered.append((frame_number, annotated))
        report_frames.append(
            {
                "frame_one_based": frame_number,
                "source": str(path),
                "output": str(output),
                "raw_contact_global": [
                    round(raw.contact_x + roi_x, 3),
                    round(raw.contact_y + roi_y, 3),
                ],
                "contact_global": [
                    round(stable.contact_x + roi_x, 3),
                    round(stable.contact_y + roi_y, 3),
                ],
                "distance_px": round(stable.distance_px, 3),
                "axial_distance_px": round(stable.axial_distance_px, 3),
                "lateral_offset_px": round(stable.lateral_offset_px, 3),
                "method": stable.method,
                "distance_mm": (
                    round(stable.distance_px * args.mm_per_pixel, 3)
                    if args.mm_per_pixel is not None
                    else None
                ),
            }
        )

    contact_sheet_path = args.output_dir / "contact_sheet.jpg"
    if rendered:
        sample_indices = (
            np.linspace(0, len(rendered) - 1, min(6, len(rendered)))
            .round()
            .astype(int)
        )
        panels = [
            _panel(rendered[index][1], f"frame {rendered[index][0]}/{len(images)}")
            for index in sample_indices
        ]
        while len(panels) % 3:
            panels.append(np.full_like(panels[0], 245))
        rows = [
            np.hstack(panels[index : index + 3])
            for index in range(0, len(panels), 3)
        ]
        cv2.imwrite(str(contact_sheet_path), np.vstack(rows), [cv2.IMWRITE_JPEG_QUALITY, 94])

    report = {
        "status": "ok",
        "sequence_dir": str(args.sequence_dir),
        "source_count": len(images),
        "reference_frame_one_based": choice.background_reference_frame,
        "trace_reference_frame_one_based": choice.trace_reference_frame,
        "trace_reference_source": choice.trace_reference_source,
        "background_reference_source": choice.background_reference_source,
        "reference_selection_method": choice.selection_method,
        "roi_xywh": list(choice.roi),
        "trace_tip_global": [
            round(trace.tip_x + roi_x, 3),
            round(trace.tip_y + roi_y, 3),
        ],
        "median_window": args.median_window,
        "contact_frame_count": len(report_frames),
        "contact_sheet": str(contact_sheet_path) if rendered else None,
        "frames": report_frames,
    }
    report_path = args.output_dir / "report.json"
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "status": "ok",
                "reference_selection_method": choice.selection_method,
                "trace_reference_frame": choice.trace_reference_frame,
                "roi_xywh": list(choice.roi),
                "contact_frames": len(report_frames),
                "first_contact_frame": (
                    report_frames[0]["frame_one_based"] if report_frames else None
                ),
                "last_contact_frame": (
                    report_frames[-1]["frame_one_based"] if report_frames else None
                ),
                "contact_sheet": report["contact_sheet"],
                "report": str(report_path),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
